/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_ThuThu;

import Main.GUI_ChooseLogin;
import Process.Process_DauSach;
import GUI_ThuThu.quanLyDauSachCard;
import GUI_ThuThu.quanLyNguoiMuonCard;
import GUI_ThuThu.quanLyPhieuMuon;
import GUI_ThuThu.quanLySachCard;
import java.awt.CardLayout;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class GUI_TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    CardLayout cardLayout;
    public GUI_TrangChu() {
        initComponents();
        this.setSize(1280, 720);
        cardLayout = (CardLayout)(UICards.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        UICards = new javax.swing.JPanel();
        quanLyDauSachCard = new javax.swing.JPanel();
        quanLySachCard = new javax.swing.JPanel();
        quanLyNguoiMuonCard = new javax.swing.JPanel();
        quanLyPhieuMuonCard = new javax.swing.JPanel();
        thongKeCard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 500));
        setPreferredSize(new java.awt.Dimension(1157, 1000));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));

        jSplitPane1.setPreferredSize(new java.awt.Dimension(1005, 900));

        jPanel1.setBackground(new java.awt.Color(66, 61, 61));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 574));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Quản lý");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 35));
        jLabel2.setPreferredSize(new java.awt.Dimension(190, 21));
        jPanel1.add(jLabel2);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/agenda.png"))); // NOI18N
        jButton1.setText("Đầu sách");
        jButton1.setDisabledSelectedIcon(null);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(7);
        jButton1.setMaximumSize(new java.awt.Dimension(200, 35));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book (1).png"))); // NOI18N
        jButton3.setText("Người mượn");
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setIconTextGap(7);
        jButton3.setMaximumSize(new java.awt.Dimension(200, 35));
        jButton3.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book (2).png"))); // NOI18N
        jButton2.setText("Sách");
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(7);
        jButton2.setMaximumSize(new java.awt.Dimension(200, 35));
        jButton2.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-card.png"))); // NOI18N
        jButton6.setText("Phiếu mượn");
        jButton6.setFocusPainted(false);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setIconTextGap(7);
        jButton6.setMaximumSize(new java.awt.Dimension(200, 35));
        jButton6.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list.png"))); // NOI18N
        jButton7.setText("Thống kê");
        jButton7.setFocusPainted(false);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setIconTextGap(7);
        jButton7.setMaximumSize(new java.awt.Dimension(200, 35));
        jButton7.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jPanel3.setBackground(new java.awt.Color(66, 61, 61));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout (1).png"))); // NOI18N
        jButton5.setText("Đăng xuất");
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setIconTextGap(7);
        jButton5.setMaximumSize(new java.awt.Dimension(200, 35));
        jButton5.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jSplitPane1.setLeftComponent(jPanel1);

        UICards.setBackground(new java.awt.Color(255, 255, 255));
        UICards.setPreferredSize(new java.awt.Dimension(800, 1081));
        UICards.setLayout(new java.awt.CardLayout());

        quanLyDauSachCard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quanLyDauSachCardLayout = new javax.swing.GroupLayout(quanLyDauSachCard);
        quanLyDauSachCard.setLayout(quanLyDauSachCardLayout);
        quanLyDauSachCardLayout.setHorizontalGroup(
            quanLyDauSachCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        quanLyDauSachCardLayout.setVerticalGroup(
            quanLyDauSachCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        UICards.add(quanLyDauSachCard, "quanLyDauSachCard");

        quanLySachCard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quanLySachCardLayout = new javax.swing.GroupLayout(quanLySachCard);
        quanLySachCard.setLayout(quanLySachCardLayout);
        quanLySachCardLayout.setHorizontalGroup(
            quanLySachCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        quanLySachCardLayout.setVerticalGroup(
            quanLySachCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        UICards.add(quanLySachCard, "quanLySachCard");

        quanLyNguoiMuonCard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quanLyNguoiMuonCardLayout = new javax.swing.GroupLayout(quanLyNguoiMuonCard);
        quanLyNguoiMuonCard.setLayout(quanLyNguoiMuonCardLayout);
        quanLyNguoiMuonCardLayout.setHorizontalGroup(
            quanLyNguoiMuonCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        quanLyNguoiMuonCardLayout.setVerticalGroup(
            quanLyNguoiMuonCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        UICards.add(quanLyNguoiMuonCard, "quanLyNguoiMuonCard");

        quanLyPhieuMuonCard.setBackground(new java.awt.Color(255, 255, 255));
        quanLyPhieuMuonCard.setMinimumSize(new java.awt.Dimension(700, 0));
        quanLyPhieuMuonCard.setPreferredSize(new java.awt.Dimension(700, 782));

        javax.swing.GroupLayout quanLyPhieuMuonCardLayout = new javax.swing.GroupLayout(quanLyPhieuMuonCard);
        quanLyPhieuMuonCard.setLayout(quanLyPhieuMuonCardLayout);
        quanLyPhieuMuonCardLayout.setHorizontalGroup(
            quanLyPhieuMuonCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        quanLyPhieuMuonCardLayout.setVerticalGroup(
            quanLyPhieuMuonCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        UICards.add(quanLyPhieuMuonCard, "quanLyPhieuMuonCard");

        thongKeCard.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout thongKeCardLayout = new javax.swing.GroupLayout(thongKeCard);
        thongKeCard.setLayout(thongKeCardLayout);
        thongKeCardLayout.setHorizontalGroup(
            thongKeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        thongKeCardLayout.setVerticalGroup(
            thongKeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        UICards.add(thongKeCard, "thongKeCard");

        jSplitPane1.setRightComponent(UICards);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(138, 25, 18));
        jPanel2.setPreferredSize(new java.awt.Dimension(1157, 70));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý dữ liệu thư viện");
        jLabel1.setPreferredSize(new java.awt.Dimension(259, 50));
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        quanLyDauSachCard GUI_DauSach = new quanLyDauSachCard();
        UICards.removeAll();
        UICards.add(GUI_DauSach);
        UICards.revalidate();
        UICards.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        quanLySachCard GUI_Sach = new quanLySachCard();
        UICards.removeAll();
        UICards.add(GUI_Sach);
        UICards.revalidate();
        UICards.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        quanLyNguoiMuonCard GUI_NguoiMuon = new quanLyNguoiMuonCard();
        UICards.removeAll();
        UICards.add(GUI_NguoiMuon);
        UICards.revalidate();
        UICards.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//        cardLayout.show(UICards, "thongKeCard");
        GUI_ThongKe thongKe = new GUI_ThongKe();
        thongKe.setLocationRelativeTo(null);  // Giua man hinh
        thongKe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        quanLyPhieuMuon GUI_PhieuMuon = new quanLyPhieuMuon();
        UICards.removeAll();
        UICards.add(GUI_PhieuMuon);
        UICards.revalidate();
        UICards.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        GUI_ChooseLogin dang_nhap = new GUI_ChooseLogin();
        dang_nhap.setLocationRelativeTo(null);  // Giua man hinh
        dang_nhap.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     *
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ChooseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ChooseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ChooseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ChooseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UICards;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel quanLyDauSachCard;
    private javax.swing.JPanel quanLyNguoiMuonCard;
    private javax.swing.JPanel quanLyPhieuMuonCard;
    private javax.swing.JPanel quanLySachCard;
    private javax.swing.JPanel thongKeCard;
    // End of variables declaration//GEN-END:variables
}
